name: upload4me

services:
  backend:
    build:
      context: ./s3-bucket-core
      dockerfile: Dockerfile
    container_name: s3-bucket-core
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./s3-bucket-core/.env
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./s3-bucket-app
      dockerfile: Dockerfile
    container_name: s3-bucket-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
